PKGDIR ?= ..
L4DIR  ?= $(PKGDIR)/../../trunk/l4

# create examples demonstrating the use of your package in subdirectories
# and list those subdirs in the TARGET variable.
TARGET = simple-example mixed-example automotive-example

include $(L4DIR)/mk/subdir.mk
