PKGDIR	?= ..
L4DIR	?= $(PKGDIR)/../../trunk/l4

# All header files found in this directory tree will be automatically
# installed in a way that they can be included with
# #include <l4/pkgname/yourfile.h> later.
# No need to list them in this Makefile.
# list requirements of your program here
REQUIRES_LIBS            = cxx_libc_io cxx_io

include $(L4DIR)/mk/include.mk
