PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../../trunk/l4

TARGET		= $(PKGNAME)

# list your .c or .cc files here
SRC_CC  = main.cc

# list requirements of your program here
REQUIRES_LIBS            = cxx_libc_io cxx_io

include $(L4DIR)/mk/prog.mk
