PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../../trunk/l4

TARGET			= test_libac_csv 
SRC_C_test_libac_csv	= main.c



REQUIRES_LIBS            = libedft cxx_libc_io cxx_io l4re_c-util  

include $(L4DIR)/mk/prog.mk
